on:
  milestone:
    types: [created]
    
jobs:
  check-contents:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # Install dependencies
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Install checker 
      run: |
        pip install git+https://github.com/introcompsys/courseutils@main
         
        
    - name: Run loop 
      run: |    
        for file in $(kwlfilecheck)
        do
         if ! test -f $file; then
          echo $file
         fi
        done
